### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by Justman10000** [masterjanic/discord-checker-web#1]
@masterjanic 

Regardless of the token, this always comes:

> GET https://discord.com/api/v9/users/@me
> 401 Unauthorized

**Comment by masterjanic** [comment]
@Justman10000 

Could you provide more details? 

What kind of token are you using (mfa or default)?

How exactly are you experiencing this error?

**Comment by Justman10000** [comment]
> What kind of token are you using (mfa or default)?

Default and mfa

> How exactly are you experiencing this error?

Checking the tokens...

**Comment by Justman10000** [comment]
@masterjanic

**Comment by masterjanic** [comment]
What browser are you using? Are you using the the public website linked in this repository or a private build?


The status code 401 indicates that your checked tokens are invalid, and the accounts should therefore be shown under the invalid section on the website.
Can you confirm that you see this?

I checked a test set of tokens 5 minutes ago and everything worked for me. So please provide more details (system information, if private build the version of the instance, how many tokens are you checking or provide a sample).

**Comment by Justman10000** [comment]
> What browser are you using? Are you using the the public website linked in this repository or a private build?

Mozilla Firefox


> The status code 401 indicates that your checked tokens are invalid, and the accounts should therefore be shown under the invalid section on the website. Can you confirm that you see this?

I know, and yes, it is displayed that way


> I checked a test set of tokens 5 minutes ago and everything worked for me. So please provide more details (system information, if private build the version of the instance, how many tokens are you checking or provide a sample).

I got my tokens from a .py token grabber, all of them are declared invalid, which can't be!

**Comment by Justman10000** [comment]
@masterjanic

**Comment by Justman10000** [comment]
Bot tokens don't work either!

**Comment by masterjanic** [comment]
There is no other explanation other than that your tokens are invalid. Of course you are free to check them with another program.

Bot tokens are currently not supported.
