### ISSUE TITLE
Whole website redirecting to a rick roll...

### ISSUE THREAD

**Issue by Sayrix** [masterjanic/discord-checker-web#10]
0 fun + cringe

**Comment by xARMR** [comment]
@masterjanic great job tf

**Comment by d0mse** [comment]
I've heard that it stays until someone appreciates the service with a noble donation. $5 is $5
**lol**

**Comment by xARMR** [comment]
> I've heard that it stays until someone appreciates the service with a noble donation. $5 is $5 **lol**

from where did u heard this?

**Comment by d0mse** [comment]
Discord

**Comment by masterjanic** [comment]
@Sayrix @xARMR The website is back online.
