### ISSUE TITLE
locked accounts

### ISSUE THREAD

**Issue by Mewzax** [masterjanic/discord-checker-web#2]
can you show locked accounts please

**Comment by masterjanic** [comment]
What do you mean by locked accounts? It already shows unverified accounts.

**Comment by Mewzax** [comment]
an account can be verified but phone locked no ?

**Comment by masterjanic** [comment]
This is already being checked. Because the verified section only shows accounts which are not locked.

If you had a look at the source code, you would have seen that an additional request is sent to `users/@me/billing/country-code`. If this request fails, the user is set to unverified.
