### ISSUE TITLE
mfa. tokens

### ISSUE THREAD

**Issue by GuFFy12** [masterjanic/discord-checker-web#3]
MFA tokens no longer supported by discord, and i don't found any valid token of this type
.

**Comment by masterjanic** [comment]
Hello and thanks for your interest in this project. Do you have any proof that mfa. tokens are disabled by now (e.g. an article)?

In that case I would remove the checks from the website code, but I will need to verify it first.

**Comment by GuFFy12** [comment]
Unfortunately I'm only based on statistics. It's just that all my mfa tokens became disabled at one moment.

**Comment by masterjanic** [comment]
I see. Thank you for letting me know. I will have a look at it 👍🏼

**Comment by GuFFy12** [comment]
Also tokens with 59 length still alive. And how you found out about the fact that the discord changed the length of the tokens? I just kept my project with an old parser that couldn't find new tokens for about 2 months!!! until it dawned on me that the discord changed the length

**Comment by masterjanic** [comment]
I was working on a websocket qr stealer and saw that the length was different. It even makes the process of checking them easier since you can now decrypt the user id from the token for every token which was not possible for mfa tokens.

**Comment by masterjanic** [comment]
This issue has been fixed with the recent changes.
