### ISSUE TITLE
discord error code 429

### ISSUE THREAD

**Issue by xNasuni** [masterjanic/discord-checker-web#7]
it seems that if you have a list of tokens for example lets say 500 there isn't a delay between them and you get response code 429, which could mean that it was actually a valid token but just didn't let you because of the rate limit, is it possible for you to make an option for it to do it slower, one by one, or wait for the `retry-after` header then redo that same request that got rate limited? i feel like the last one would be the smartest choice and i don't know if this is only happening to me
![image](https://github.com/masterjanic/discord-checker-web/assets/62818119/3b79675b-df56-436f-a85f-e124fc228e35)

**Comment by masterjanic** [comment]
Hello!

I have already implemented such feature. If the checker encounters a 429 error it waits and then tries again after 5 seconds.

As I can see in your request history though is that you disabled your cache in the Developer Tools, resulting in a massive number of Preflight Requests which is propably the cause for all your failed requests.

Try enabling your cache again and see if the issue resolves, you can find the option at the top of your Developer Tools window.

**Comment by xNasuni** [comment]
you are right, my cache was disabled for some reason, but it still should wait for the `retry_after` header for max efficiency instead of 5 seconds right?
