### ISSUE TITLE
Broken Site Argo Tunnel error

### ISSUE THREAD

**Issue by xARMR** [masterjanic/discord-checker-web#9]
Error 1033 Ray ID: 8137b904b966d184 • 2023-10-09 15:40:33 UTC
Argo Tunnel error
What happened?
You've requested a page on a website (discord-checker.janic.dev) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (discord-checker.janic.dev) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Ensure that cloudflared is running and can reach the network. You may wish to enable [load balancing](https://developers.cloudflare.com/argo-tunnel/reference/load-balancing/) for your tunnel.

**Comment by xARMR** [comment]
Check ur website ://

**Comment by NxyyLOL** [comment]
@masterjanic 
@masterjanic

**Comment by masterjanic** [comment]
Resolved.
